FROM node:20-alpine AS base

# Stage for general setup
FROM base AS general
RUN apk update
WORKDIR /app
COPY . .

# Stage for installing dependencies and building the project
FROM base AS installer
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app
COPY --from=general /app/out/package-lock.json ./package-lock.json
COPY --from=general /app/out/full/apps/web/package.json ./package.json
RUN npm install --frozen-lockfile

COPY --from=general /app/out/full/apps/web .
RUN npm run build

# Stage for running the application
FROM nginx:alpine as runner
WORKDIR /var/www
COPY apps/web/nginx/nginx.conf /etc/nginx/nginx.conf
COPY apps/web/nginx/mime.types /etc/nginx/mime.types
COPY apps/web/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=installer /app/dist .
EXPOSE 80
